name: Deploy on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x] # Mengubah versi Node.js menjadi 14.x karena 20.x tidak ada
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Mengubah versi Node.js menjadi 14.x
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server: ocinz.biz.id 
          server-dir: /
          local-dir: ./dist/
